environment:
  matrix:
#    - PYTHON: "C:\\Python27"
#      PYTHON_VERSION: "2.7.8"
#      PYTHON_ARCH: "32"
#
#    - PYTHON: "C:\\Python33"
#      PYTHON_VERSION: "3.3.5"
#      PYTHON_ARCH: "32"
#
#    - PYTHON: "C:\\Python34"
#      PYTHON_VERSION: "3.4.1"
#      PYTHON_ARCH: "32"
#
    - PYTHON: "C:\\Python27_64"
      PYTHON_VERSION: "2.7.8"
      PYTHON_ARCH: "64"
      WINDOWS_SDK_VERSION: "v7.0"
#
#    - PYTHON: "C:\\Python33_64"
#      PYTHON_VERSION: "3.3.5"
#      PYTHON_ARCH: "64"
#      WINDOWS_SDK_VERSION: "v7.1"
#
#    - PYTHON: "C:\\Python34_64"
#      PYTHON_VERSION: "3.4.1"
#      PYTHON_ARCH: "64"
#      WINDOWS_SDK_VERSION: "v7.1"


init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "powershell appveyor\\install.ps1"
  - '"C:\Program Files\Microsoft SDKs\Windows\%WINDOWS_SDK_VERSION%\Bin\SetEnv.cmd" /x64 /release'

build: off

test_script:
  - "%PYTHON%/python setup.py test"

after_test:
  - "%PYTHON%/python setup.py bdist_wheel"

artifacts:
  - path: dist\*

#on_success:
#  - TODO: upload the content of dist/*.whl to a public wheelhouse
